#!/bin/sh
# Requires pdflatex

FILENAME=simon-fish_zheming-qiu
pdflatex "$FILENAME.tex"

# Delete compile files
rm "$FILENAME.aux" "$FILENAME.out" "$FILENAME.log" "$FILENAME.fls" "$FILENAME.fdb_latexmk"
